# Generated by Django 3.1.1 on 2020-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='gear',
            field=models.SmallIntegerField(choices=[(1, 'механика'), (2, 'автомат'), (3, 'робот')], default=1, verbose_name='cars_gear'),
        ),
    ]
