# Generated by Django 3.1.1 on 2020-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200927_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.CharField(max_length=255, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='gear',
            field=models.SmallIntegerField(choices=[(1, 'механика'), (2, 'автомат'), (3, 'робот')], verbose_name='cars_gear'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mark',
            field=models.CharField(max_length=255, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
    ]
